name: pihole
version: 2.9.6
summary: A black hole for Internet advertisements
description: |
  Pi-hole is a DNS-based, platform-agnostic, network-wide ad blocker.
# vendor: Pi-hole, LLC.  <adblock@pi-hole.net>
# icon: meta/Vortex.png
grade: devel
confinement: devmode

apps:
  # This is the custom provisioning script
  # Pi-hole needs to setup a DNS/Web server combo and these services
  # require special config files for it to work correctly
  # It runs as a daemon so it will provision the system automatically
  wrapper:
    command: bin/wrapper
    daemon: simple
    plugs:
      - content

  # Pi-hole is a DNS server at it's core, so we need to install a resolver
  # dnsmasq apps/parts forked from https://github.com/lool/dnsmasq-snap
  # dnsmasq:
  #   command: bin/dnsmasq -C config/dnsmasq.conf
  #   daemon: forking
  #   # The DNS server needs access to the network to function properly
  #   plugs:
  #     # Can access the network as a client
  #     - network
  #     # Can access the network as a server
  #     - network-bind
  #     # Can configure networking which gives wide, privileged access to networking
  #     - network-control
  #     - content

parts:
  # dnsmasq:
  #   plugin: make
  #   source: git://thekelleys.org.uk/dnsmasq.git
  #   organize:
  #     usr/local/sbin/dnsmasq: bin/dnsmasq
  #   # A list of files from a part’s installation to expose in the snap
  #   snap:
  #     - bin/dnsmasq
  #   after:
  #     - files-to-copy
  files-to-copy:
    # We need several supplemental files for the DNS and Web servers
    # Just use the dump plugin to copy them over
    plugin: dump
    source: .
    organize:
      # We need a custom config file for Pi-hole to run as a DNS server
      dnsmasq.conf: config/dnsmasq.conf
      # Additional hosts file for the DNS server to use
      gravity.list: config/gravity.list
      # bash script that loads and replaces values in the config file(s)
      wrapper: bin/wrapper
