name: pihole
version: 4.0
summary: Network infrastructure swiss-army knife
description: |
  Dnsmasq provides network infrastructure for small networks: DNS, DHCP, router
  advertisement and network boot. It is designed to be lightweight and have a
  small footprint, suitable for resource constrained routers and firewalls. 
grade: stable
confinement: devmode

apps:
  setup:
    command: bin/setup
    plugs:
      - network
      - network-control
  pihole-debug:
    command: bin/pihole-FTL debug
    plugs:
      - network
      - network-bind
      - network-control
  pihole-daemon:
    daemon: simple
    command: bin/wrapper
    plugs:
      - network
      - network-bind
      - network-control

parts:
  nettle: 
    source: https://ftp.gnu.org/gnu/nettle/nettle-3.4.tar.gz
    plugin: autotools
    install-via: prefix
    override-build: |
      ./configure --exec-prefix=/usr/local
      make
      make install
  gmp: 
    after: [nettle]
    source: https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2
    plugin: autotools
    override-build: |
      export CFLAGS="-fPIC"
      ./configure
      make
      make install
  pihole-ftl:
    after: [nettle,gmp,patches]
    source: https://github.com/pi-hole/FTL.git
    plugin: make
    build-packages:
      - libnetfilter-conntrack-dev
      - libidn11-dev
      - m4
      - build-essential
      - libhogweed4
    stage-packages:
      - whiptail
      - curl
      - dialog
    override-pull: |
      snapcraftctl pull
      patch -p1 --verbose < $SNAPCRAFT_STAGE/fix-confined-paths.patch
    override-build: |
      snapcraftctl build
      install -D pihole-FTL $SNAPCRAFT_PART_INSTALL/bin/pihole-FTL
  wrapper:
    plugin: dump
    source: .
    organize:
      wrapper: bin/wrapper
      setup: bin/setup
  patches:
    source: patches
    plugin: dump
